name: Release

on:
  workflow_dispatch:  # trigger it manually

permissions:
  packages: write

env:
  QBT_VERSION: "4.5.0"

  # This is a positive integer number that allows to differentiate between consecutive builds of the same qBittorrent version.
  # When `QBT_VERSION` is incremented, this value must be reset to 1.
  TAG_RELEASE_NUMBER: 3

  PLATFORMS: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8"

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [worker.oci]
              max-parallelism = 1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            QBT_VERSION=${{ env.QBT_VERSION }}
          platforms: ${{ env.PLATFORMS }}
          push: true
          labels: |
            org.opencontainers.image.description=An advanced BitTorrent client programmed in C++, based on Qt toolkit and libtorrent-rasterbar
            org.opencontainers.image.documentation=https://github.com/qbittorrent/docker-qbittorrent-nox
            org.opencontainers.image.licenses=GPL-3.0+
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/qbittorrent/docker-qbittorrent-nox
            org.opencontainers.image.title=qbittorrent-nox docker image
            org.opencontainers.image.url=https://github.com/qbittorrent/docker-qbittorrent-nox
            org.opencontainers.image.vendor=qBittorrent
            org.opencontainers.image.version=${{ env.QBT_VERSION }}
          tags: |
            qbittorrentofficial/qbittorrent-nox:${{ env.QBT_VERSION }}-${{ env.TAG_RELEASE_NUMBER }}
            qbittorrentofficial/qbittorrent-nox:latest
            ghcr.io/qbittorrent/docker-qbittorrent-nox:${{ env.QBT_VERSION }}-${{ env.TAG_RELEASE_NUMBER }}
            ghcr.io/qbittorrent/docker-qbittorrent-nox:latest
